### ISSUE TITLE
func manager更新函数路由 源topic 并同步配置后，原topic仍然work

### ISSUE THREAD

**Issue by gigi5700** [baidu/openedge#187]
如图，由t改成r。
下发配置后，往t和r发消息函数路由均work
![image](https://user-images.githubusercontent.com/36956936/55539499-5aaf7280-56f3-11e9-8f0c-bd2aaad49047.png)

**Comment by gigi5700** [comment]
类似问题也存在remote模块配置的topic、接入上

**Comment by ludanfeng** [comment]
主题调整目前需要修改clientid，因为默认cleansession为false，重连会自动订阅之前的主题

**Comment by ludanfeng** [comment]
If you are using bridges/remotes with cleansession set to false (the default), then you may get unexpected behaviour from incoming topics if you change what topics you are subscribing to. This is because the remote broker keeps the subscription for the old topic. If you have this problem, connect your bridge with cleansession set to true, then reconnect with cleansession set to false as normal.
