### ISSUE TITLE
example sayhi seems not work

### ISSUE THREAD

**Issue by tongtongxiaopeng1979** [baidu/openedge#42]
By using sayhi in the example, tried function computing , but failed with ""errorMessage": "rpc error: code = Unknown desc = Exception calling application","

checked every step i have done, not find any clues, please help , thanks

**Comment by kuailehaibin** [comment]
@tongtongxiaopeng1979 

Hi, according to `sayhi log`, the problem is "Exception calling application: 'USER_ID'". The right way about variable "USER_ID" should be that: 

> + firstly it shouble be defined in `conf.yml`(openedge_hub module config)
> + then it can be used in `index.py`

But, as the `conf.yml`(openedge_hub module config) you provide, it cannot be found.

Two methods to solve this problem:

> 1. add "USER_ID" config info in `conf.yml`(openedge_hub module config), it can be found [here](https://github.com/baidu/openedge/blob/master/example/docker/var/db/openedge/module/localfunc/module.yml)
> 2. add judgment logic at `index.py`.

That's all, many thanks for your problem feedback.

**Comment by tongtongxiaopeng1979** [comment]
thanks, it works according to your guide. :)
